# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c8e8728f9b7b5d6a71a6d5e86e0d458d9ec1d921b5a09eedf994e19a9c39aa1f4d180a21db409367fe79943fb57b0a3cfd90450ddbf7995f549b362bec81f568

test:
  secret_key_base: 2ab160e5580ca566c88baa606f0fd22f87cd918714d23a715d896e60dc8ba1e50dfa512497bcc1be51a1fdaadf69039e3165776ee2a530ce9084e530353911ac

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
